#!/usr/bin/env python3
"""Regenerate `docs/TRACE-MATRIX.md` from requirement documents and test markers.

The matrix is the single source of truth for requirement *status*. The three
requirement documents carry only specification content, and the tests carry
only markers; neither records whether anything is done. Deriving status instead
of writing it down is what stops the documentation from claiming coverage that
the test suite does not actually provide.

Inputs
------
1. `docs/L1.md` \u2014 L1 ids, declared verification methods, optional evidence.
2. `docs/L2.md` \u2014 L2 ids with a `**Parent**:` line naming an L1.
3. `docs/L3.md` \u2014 L3 ids in the compact one-line form, each naming an L2 parent.
4. `tests/` \u2014 every id appearing in a `@pytest.mark.requirement(...)` marker,
   collected by parsing the AST rather than by regex, so a marker split across
   lines or built from a constant is still seen.

Status rollup
-------------
A leaf requirement is **Implemented** when at least one test marker names it.
A leaf verified only by Inspection, Analysis or Demonstration cannot have a
test marker, so it reaches **Implemented (I/A/D)** instead \u2014 but only when it
also declares an `**Evidence**` line naming what actually carries the check. A
declared method with no evidence is a plan rather than a result, and stays
**Draft**, exactly as an unmarked test-verified leaf does.

A parent is **Implemented** when every child is, **Draft** when none are, and
**Partially Implemented** in between.

Usage:
    python scripts/build-trace-matrix.py           # regenerate in place
    python scripts/build-trace-matrix.py --check   # fail if the file drifted
"""

# The hyphenated filename is deliberate: this is a command, not an importable
# module. pylint checks it against module naming rules regardless.
# pylint: disable=invalid-name

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
L1_DOC = ROOT / "docs" / "L1.md"
L2_DOC = ROOT / "docs" / "L2.md"
L3_DOC = ROOT / "docs" / "L3.md"
TRACE_DOC = ROOT / "docs" / "TRACE-MATRIX.md"
TESTS_DIR = ROOT / "tests"

MARKER_NAME = "requirement"
"""The pytest marker whose arguments name requirement ids."""

GENERATED_BANNER = "<!-- AUTO-GENERATED by scripts/build-trace-matrix.py. Do not edit by hand. -->"

# --- Document grammar ------------------------------------------------------
# L1 and L2 requirements are headed sections carrying metadata lines. L3s are
# single lines, because at implementation level the statement is usually one
# sentence and a full section per item buries it.
L1_HEADER = re.compile(r"^###\s+(L1-[A-Z]+-\d+)\s*$", re.MULTILINE)
L2_HEADER = re.compile(r"^####\s+(L2-[A-Z]+-\d+)\s*$", re.MULTILINE)
L3_LINE = re.compile(
    r"^\*\*(L3-[A-Z]+-\d+)\*\*\s*\u00b7\s*Parent:\s*(L2-[A-Z]+-\d+)\s*\u00b7\s*"
    r"Verification:\s*([^\u00b7\n]+?)\s*(?:\u00b7\s*Evidence:\s*([^\n]+?)\s*)?$",
    re.MULTILINE,
)
PARENT_LINE = re.compile(r"^\*\*Parent\*\*:\s*(L1-[A-Z]+-\d+)\s*$", re.MULTILINE)
# `\s` matches a newline, so `\s*` next to `[^\n]+` under re.MULTILINE
# lets the two compete for the same characters and backtrack super-
# linearly on a line that nearly matches. `[^\S\n]` is horizontal
# whitespace only, which is what these patterns meant.
HORIZONTAL = r"[^\S\n]*"

METHOD_LINE = re.compile(rf"^\*\*Verification Method\*\*:{HORIZONTAL}([^\n]+)$", re.MULTILINE)
EVIDENCE_LINE = re.compile(rf"^\*\*Evidence\*\*:{HORIZONTAL}([^\n]+)$", re.MULTILINE)
CATEGORY_ROW = re.compile(
    rf"^\|{HORIZONTAL}`([A-Z]+)`{HORIZONTAL}\|{HORIZONTAL}([^|\n]+?){HORIZONTAL}\|{HORIZONTAL}$",
    re.MULTILINE,
)
METHOD_LETTER = re.compile(r"\b([TIAD])\b")

NONE_CELL = "_(none)_"
"""Placeholder for a table cell with nothing to list."""

STATUS_DRAFT = "Draft"
STATUS_IMPLEMENTED = "Implemented"
STATUS_PARTIAL = "Partially Implemented"


def _sections(text: str, header: re.Pattern[str]) -> dict[str, str]:
    """Split a requirement document into `{id: body}` by header matches.

    Args:
        text: The whole document.
        header: Pattern whose first group is the requirement id.

    Returns:
        Each requirement id mapped to the text between its header and the next.
    """
    matches = list(header.finditer(text))
    sections: dict[str, str] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        sections[match.group(1)] = text[match.end() : end]
    return sections


def _methods(body: str) -> set[str]:
    """Extract DO-178 verification letters from a requirement body."""
    match = METHOD_LINE.search(body)
    if match is None:
        return set()
    return set(METHOD_LETTER.findall(match.group(1)))


def _evidence(body: str) -> list[str]:
    """Extract the backticked artifacts named on an `**Evidence**` line."""
    match = EVIDENCE_LINE.search(body)
    if match is None:
        return []
    found = re.findall(r"`([^`]+)`", match.group(1))
    return found or [match.group(1).strip()]


def parse_categories() -> dict[str, str]:
    """Read the category code/title tables from the L1 and L2 documents.

    Titles come from the documents rather than from a table in this script, so
    adding a category is a one-place edit.

    Returns:
        Category code mapped to its human-readable title.
    """
    categories: dict[str, str] = {}
    for doc in (L1_DOC, L2_DOC):
        if not doc.exists():
            continue
        for code, title in CATEGORY_ROW.findall(doc.read_text(encoding="utf-8")):
            categories.setdefault(code, title.strip())
    return categories


def parse_l1() -> dict[str, tuple[set[str], list[str]]]:
    """Parse L1 ids with their verification methods and evidence."""
    text = L1_DOC.read_text(encoding="utf-8")
    return {
        req_id: (_methods(body), _evidence(body))
        for req_id, body in _sections(text, L1_HEADER).items()
    }


def parse_l2() -> dict[str, tuple[str, set[str], list[str]]]:
    """Parse L2 ids with their parent L1, verification methods and evidence.

    Raises:
        SystemExit: If an L2 declares no parent, which would silently drop it
            out of the forward trace.
    """
    text = L2_DOC.read_text(encoding="utf-8")
    parsed: dict[str, tuple[str, set[str], list[str]]] = {}
    for req_id, body in _sections(text, L2_HEADER).items():
        parent = PARENT_LINE.search(body)
        if parent is None:
            raise SystemExit(f"{L2_DOC.name}: {req_id} has no **Parent**: line")
        parsed[req_id] = (parent.group(1), _methods(body), _evidence(body))
    return parsed


def parse_l3() -> dict[str, tuple[str, set[str], list[str]]]:
    """Parse the compact one-line L3 entries."""
    text = L3_DOC.read_text(encoding="utf-8")
    parsed: dict[str, tuple[str, set[str], list[str]]] = {}
    for req_id, parent, methods, evidence in L3_LINE.findall(text):
        artifacts = re.findall(r"`([^`]+)`", evidence) if evidence else []
        if evidence and not artifacts:
            artifacts = [evidence.strip()]
        parsed[req_id] = (parent, set(METHOD_LETTER.findall(methods)), artifacts)
    return parsed


def _marker_ids(decorator: ast.expr) -> list[str]:
    """Return the requirement ids named by one decorator, if it is our marker.

    Args:
        decorator: A decorator node from a test function.

    Returns:
        Every string literal argument, or an empty list when the decorator is
        not `@pytest.mark.requirement(...)`.
    """
    if not isinstance(decorator, ast.Call):
        return []
    target = decorator.func
    if not isinstance(target, ast.Attribute) or target.attr != MARKER_NAME:
        return []
    # The chain must be `pytest.mark.requirement`, not some other `.requirement`.
    owner = target.value
    if not isinstance(owner, ast.Attribute) or owner.attr != "mark":
        return []
    return [
        argument.value
        for argument in decorator.args
        if isinstance(argument, ast.Constant) and isinstance(argument.value, str)
    ]


def collect_markers(tests_dir: Path) -> dict[str, list[str]]:
    """Harvest requirement markers from every test module.

    Args:
        tests_dir: Directory to walk.

    Returns:
        Requirement id mapped to sorted `path::test_name` artifacts.
    """
    found: dict[str, set[str]] = defaultdict(set)
    for path in sorted(tests_dir.rglob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        relative = path.relative_to(ROOT).as_posix()
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in node.decorator_list:
                for req_id in _marker_ids(decorator):
                    found[req_id].add(f"{relative}::{node.name}")
    return {req_id: sorted(artifacts) for req_id, artifacts in found.items()}


def compute_status(
    *,
    has_artifacts: bool,
    children: list[str],
    methods: set[str],
    evidence: list[str],
) -> str:
    """Roll up the status of one requirement node.

    Args:
        has_artifacts: Whether a test marker names this requirement directly.
        children: Statuses of derived requirements, empty for a leaf.
        methods: Declared DO-178 verification letters.
        evidence: Artifacts named on the `**Evidence**` line.

    Returns:
        One of `Draft`, `Implemented`, `Implemented (X)`, or
        `Partially Implemented`.
    """

    def non_test() -> str | None:
        """`Implemented (\u2026)` for an evidenced I/A/D leaf, else None."""
        if not methods or "T" in methods:
            return None
        if not evidence:
            return None
        return f"{STATUS_IMPLEMENTED} ({'+'.join(sorted(methods))})"

    if not children:
        if has_artifacts:
            return STATUS_IMPLEMENTED
        return non_test() or STATUS_DRAFT

    implemented = sum(1 for status in children if status.startswith(STATUS_IMPLEMENTED))
    if implemented == len(children):
        return STATUS_IMPLEMENTED
    if implemented == 0 and not has_artifacts:
        return non_test() or STATUS_DRAFT
    return STATUS_PARTIAL


def _category(req_id: str) -> str:
    """The category code embedded in a requirement id."""
    return req_id.split("-")[1]


def _sort_key(req_id: str) -> tuple[str, int]:
    """Sort requirement ids by category then numeric sequence."""
    parts = req_id.split("-")
    return (parts[1], int(parts[2]))


def _cell(artifacts: list[str]) -> str:
    """Render an artifact list as one table cell."""
    if not artifacts:
        return NONE_CELL
    return "<br>".join(f"`{artifact}`" for artifact in artifacts)


@dataclass(frozen=True)
class Trace:
    """The whole requirement graph, with status already rolled up.

    Assembled once by `load_trace` so that rendering is a pure function of it.
    Keeping the two apart is what stops the renderer from silently recomputing
    a status differently from the way the coverage summary counted it.
    """

    categories: dict[str, str]
    l1: dict[str, tuple[set[str], list[str]]]
    l2: dict[str, tuple[str, set[str], list[str]]]
    l3: dict[str, tuple[str, set[str], list[str]]]
    markers: dict[str, list[str]]
    l2_by_parent: dict[str, list[str]]
    l3_by_parent: dict[str, list[str]]
    l1_status: dict[str, str]
    l2_status: dict[str, str]
    l3_status: dict[str, str]

    def artifacts(self, req_id: str, evidence: list[str]) -> list[str]:
        """Test markers for a requirement, falling back to its declared evidence."""
        return self.markers.get(req_id, []) or evidence


def load_trace() -> Trace:
    """Parse every input and roll status up from L3 to L1.

    Returns:
        The assembled requirement graph.

    Raises:
        SystemExit: If a test marker names a requirement no document declares.
            Failing here is deliberate: a typo in a marker would otherwise read
            as an untested requirement rather than as the mistake it is.
    """
    l1 = parse_l1()
    l2 = parse_l2()
    l3 = parse_l3()
    markers = collect_markers(TESTS_DIR)

    unknown = sorted(set(markers) - set(l1) - set(l2) - set(l3))
    if unknown:
        raise SystemExit(
            "test markers name requirements that no document declares: " + ", ".join(unknown)
        )

    l3_by_parent: dict[str, list[str]] = defaultdict(list)
    for req_id, (parent, _, _) in l3.items():
        l3_by_parent[parent].append(req_id)

    l2_by_parent: dict[str, list[str]] = defaultdict(list)
    for req_id, (parent, _, _) in l2.items():
        l2_by_parent[parent].append(req_id)

    l3_status = {
        req_id: compute_status(
            has_artifacts=bool(markers.get(req_id)),
            children=[],
            methods=methods,
            evidence=evidence,
        )
        for req_id, (_, methods, evidence) in l3.items()
    }
    l2_status = {
        req_id: compute_status(
            has_artifacts=bool(markers.get(req_id)),
            children=[l3_status[child] for child in sorted(l3_by_parent[req_id], key=_sort_key)],
            methods=methods,
            evidence=evidence,
        )
        for req_id, (_, methods, evidence) in l2.items()
    }
    l1_status = {
        req_id: compute_status(
            has_artifacts=bool(markers.get(req_id)),
            children=[l2_status[child] for child in sorted(l2_by_parent[req_id], key=_sort_key)],
            methods=methods,
            evidence=evidence,
        )
        for req_id, (methods, evidence) in l1.items()
    }

    return Trace(
        categories=parse_categories(),
        l1=l1,
        l2=l2,
        l3=l3,
        markers=markers,
        l2_by_parent=l2_by_parent,
        l3_by_parent=l3_by_parent,
        l1_status=l1_status,
        l2_status=l2_status,
        l3_status=l3_status,
    )


def _render_preamble(trace: Trace) -> list[str]:
    """Render the title, status vocabulary and coverage summary."""
    counted = list(trace.l2_status.values()) + list(trace.l3_status.values())
    done = sum(1 for status in counted if status.startswith(STATUS_IMPLEMENTED))
    percent = (100.0 * done / len(counted)) if counted else 0.0

    return [
        "# GitHub-Metrics \u2014 Requirements Trace Matrix",
        "",
        GENERATED_BANNER,
        "",
        "## Purpose",
        "",
        "Forward trace from L1 through L2 and L3 to verification artifacts. This file is",
        "regenerated from `L1.md`, `L2.md`, `L3.md`, and the `@pytest.mark.requirement`",
        "markers in `tests/` each time `scripts/build-trace-matrix.py` runs. CI runs it",
        "with `--check`, so the matrix cannot drift from the suite that backs it.",
        "",
        "## Status vocabulary",
        "",
        "- **Draft** \u2014 test verification is required but no marker names this requirement.",
        "- **Implemented** \u2014 a marker names it (leaf), or every child is Implemented.",
        "- **Implemented (I)** / **(A)** / **(D)** \u2014 verified by Inspection, Analysis or",
        "  Demonstration only, *and* an `**Evidence**` line names what carries the check.",
        "  A declared method with no evidence is a plan, not a result, and stays Draft.",
        "- **Partially Implemented** \u2014 some children are Implemented and others are not.",
        "",
        "## Coverage summary",
        "",
        f"- L1 requirements: {len(trace.l1)}",
        f"- L2 requirements: {len(trace.l2)}",
        f"- L3 requirements: {len(trace.l3)}",
        f"- Verified L2+L3: {done} of {len(counted)} ({percent:.1f}%)",
        "",
        "L1 rows are excluded from the denominator: they are verified transitively",
        "through their children, so counting them too would count the same work twice.",
        "",
        "---",
        "",
    ]


def _render_category(trace: Trace, code: str) -> list[str]:
    """Render the tables for one requirement category."""
    lines = [f"### {code}: {trace.categories.get(code, code)}", ""]

    parents = sorted((req for req in trace.l1 if _category(req) == code), key=_sort_key)
    if parents:
        lines += [
            "**L1 \u2192 L2**",
            "",
            "| L1 ID | L2 Children | Test Artifacts | Status |",
            "|-------|-------------|----------------|--------|",
        ]
        for req_id in parents:
            children = sorted(trace.l2_by_parent[req_id], key=_sort_key)
            lines.append(
                f"| {req_id} | {', '.join(children) or NONE_CELL} "
                f"| {_cell(trace.markers.get(req_id, []))} | {trace.l1_status[req_id]} |"
            )
        lines.append("")

    mids = sorted((req for req in trace.l2 if _category(req) == code), key=_sort_key)
    if mids:
        lines += [
            "**L2 \u2192 L3 \u2192 Verification Artifacts**",
            "",
            "| L2 ID | Parent | L3 Children | Test Artifacts | Status |",
            "|-------|--------|-------------|----------------|--------|",
        ]
        for req_id in mids:
            parent, _, evidence = trace.l2[req_id]
            children = sorted(trace.l3_by_parent[req_id], key=_sort_key)
            lines.append(
                f"| {req_id} | {parent} | {', '.join(children) or NONE_CELL} "
                f"| {_cell(trace.artifacts(req_id, evidence))} | {trace.l2_status[req_id]} |"
            )
        lines.append("")

    leaves = sorted((req for req in trace.l3 if _category(req) == code), key=_sort_key)
    if leaves:
        lines += [
            "**L3 \u2192 Verification Artifacts**",
            "",
            "| L3 ID | Parent | Test Artifacts | Status |",
            "|-------|--------|----------------|--------|",
        ]
        for req_id in leaves:
            parent, _, evidence = trace.l3[req_id]
            lines.append(
                f"| {req_id} | {parent} | {_cell(trace.artifacts(req_id, evidence))} "
                f"| {trace.l3_status[req_id]} |"
            )
        lines.append("")

    return lines


def build_matrix() -> str:
    """Render the whole trace matrix document.

    Returns:
        The complete Markdown text, ending in a newline.
    """
    trace = load_trace()
    lines = _render_preamble(trace)
    for code in sorted({_category(req) for req in [*trace.l1, *trace.l2, *trace.l3]}):
        lines += _render_category(trace, code)
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    """Regenerate or verify the trace matrix.

    Args:
        argv: Command line arguments, defaulting to `sys.argv[1:]`.

    Returns:
        Process exit status: 0 on success, 1 when `--check` finds drift.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit non-zero if the committed matrix is stale.",
    )
    args = parser.parse_args(argv)

    rendered = build_matrix()

    if args.check:
        current = TRACE_DOC.read_text(encoding="utf-8") if TRACE_DOC.exists() else ""
        if current != rendered:
            print(
                f"{TRACE_DOC.relative_to(ROOT).as_posix()} is out of date; "
                "run: python scripts/build-trace-matrix.py",
                file=sys.stderr,
            )
            return 1
        print(f"{TRACE_DOC.relative_to(ROOT).as_posix()} is up to date")
        return 0

    TRACE_DOC.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" so regenerating on Windows does not rewrite every line, which
    # would bury the real change in the diff and fight .gitattributes.
    with TRACE_DOC.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print(f"wrote {TRACE_DOC.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
